version: "3.9"

services:
  app:
    build: .
    container_name: gin-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "sleep 15 && ./server"


  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
